# Generated by Django 6.0.7 on 2026-07-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emp_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeprofile",
            name="hire_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
