# Generated by Django 6.0.7 on 2026-07-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emp_app", "0002_alter_employeeprofile_hire_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employeeimage",
            options={"ordering": ["order"]},
        ),
        migrations.RemoveField(
            model_name="employeeimage",
            name="order_index",
        ),
        migrations.AddField(
            model_name="employeeimage",
            name="order",
            field=models.PositiveIntegerField(default=1, verbose_name="Порядок фото"),
        ),
    ]
