# Generated by Django 6.0.7 on 2026-07-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emp_app", "0003_alter_employeeimage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="years_of_experience",
            field=models.IntegerField(default=0),
        ),
    ]
